name: budget_app
description: Application de gestion budgétaire avec connexion à Boursorama

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  fl_chart: ^0.62.0
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  lottie: ^3.0.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Networking & API
  dio: ^5.4.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  
  # Utilities
  uuid: ^4.3.3
  logger: ^2.0.2+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700 